<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hamster" nsURI="http://www.mpw.uni-stuttgart.de/hamster" nsPrefix="hamster">
  <eClassifiers xsi:type="ecore:EClass" name="Hamster" eSuperTypes="http://www.mpw.uni-stuttgart.de/mpw#//Actor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Class for Hamster in the Hamster Simulator. This class allows to initialize&#xA;Hamsters, command Hamsters through their territory and query their state."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grains" upperBound="-1"
        eType="#//Grain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Territory" eSuperTypes="http://www.mpw.uni-stuttgart.de/mpw#//Stage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The territory is a Stage which represents territories for hamsters. Territories&#xA;are rectangular areas with width and height composed out of territory&#xA;tiles. Tiles again can contain hamster objects, grain objects, or walls."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultHamster" lowerBound="1"
        eType="#//Hamster" changeable="false" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the default hamster of this territory."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Grain" eSuperTypes="http://www.mpw.uni-stuttgart.de/mpw#//Prop">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A prop which represents grain to be picked or put by a hamster."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wall" eSuperTypes="http://www.mpw.uni-stuttgart.de/mpw#//Prop">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A prop which represents a blocking content on a tile. A hamster&#xA;cannot be moved on a tile, if a wall is contained."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HamsterGame" eSuperTypes="http://www.mpw.uni-stuttgart.de/mpw#//MiniProgrammingWorld">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A MiniProgrammingWorld representing an instance of a hamster game. A hamster game consists of a territory, on&#xA;which the game takes place, a game log for messages, and a command stack for keeping track of the&#xA;game's history."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="territory" lowerBound="1"
        eType="#//Territory" changeable="false" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
